#!/bin/bash
set -e

domain=${1:-vt.edu}

while read rank data; do
	echo "Submitting and logging $data ($rank bits off target)"
best=$rank
	# TODO: log to file
	echo "$rank $data" >> submit-log
	curl --data "hashable=$data" "http://almamater.xkcd.com/?edu=$domain" >/dev/null 2>&1
done
